### ISSUE TITLE
Overly generic clock gives rise to compilation error

### ISSUE THREAD

**Issue by ivanperez-keera** [nasa/ogma#29]
The use of a generic signature for the clock in the generated Copilot code introduced in #22 gives rise to a compilation error. Copilot is unable to produce valid code from the resulting specification, even though the Haskell code produced is valid.
